### ISSUE TITLE
Gulp Build error

### ISSUE THREAD

**Issue by kinect3000** [VerizonCraft/Boxel-demo#5]
<code>
MacBook-Pro:web (user)$ gulp build
[10:16:10] Requiring external module babel-core/register
[10:16:11] Using gulpfile ~/Boxel-demo/web/gulpfile.babel.js
[10:16:11] Starting 'styles'...
[10:16:15] Starting 'images'...
[10:16:22] Starting 'fonts'...
[10:16:23] 'fonts' errored after 435 ms
[10:16:23] Error: Bower components directory does not exist at /Users/(user)/Boxel-demo/web/bower_components
    at Error (native)
    at module.exports (/Users/(user)/Boxel-demo/web/node_modules/main-bower-files/lib/index.js:76:17)
    at Gulp.<anonymous> (/Users/(user)/Boxel-demo/web/gulpfile.babel.js:74:46)
    at module.exports (/Users/(user)/Boxel-demo/web/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/(user)/Boxel-demo/web/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/(user)/Boxel-demo/web/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/(user)/Boxel-demo/web/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at Function.Module.runMain (module.js:469:11)
    at startup (node.js:136:18)
    at node.js:963:3
[10:16:23] Finished 'images' after 7.75 s
Error in plugin 'sass'
Message:
    app/styles/main.scss
Error: File to import not found or unreadable: bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss
       Parent style sheet: stdin
        on line 4 of stdin
>> @import "bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
   ^
</code>
[10:16:23] Finished 'styles' after 12 s

**Comment by kinect3000** [comment]
When i do 'gulp serve:dist' it opens up a page saying 'Cannot GET /'
There are no errors running 'gulp serve:dist'
